// Rust MD inner loop: pairwise LJ + Coulomb forces with optional AVX-512 SIMD.
// Build with --features avx512 on x86-64 to enable the 16-wide kernel;
// the scalar fallback is used automatically on all other targets.
// Python bindings are generated by PyO3; see Engine::step and energy_grad_latent.

#![allow(non_snake_case)]

use ndarray::{Array1, Array2, ArrayView1};
use pyo3::prelude::*;
use pyo3::exceptions::PyValueError;
use std::marker::PhantomData;

#[cfg(feature = "avx512")]
use std::arch::x86_64::*;

// ── Constants ────────────────────────────────────────────────────────────────

const COULOMB_K:    f32 = 332.0636; // kcal·Å / (mol·e²)
const LJ_CUTOFF:    f32 = 12.0;     // Å
const LJ_CUTOFF_SQ: f32 = LJ_CUTOFF * LJ_CUTOFF;

// ── Error type ───────────────────────────────────────────────────────────────

#[derive(thiserror::Error, Debug)]
pub enum EngineError {
    #[error("Atom count mismatch: positions={0}, params={1}")]
    AtomCountMismatch(usize, usize),
    #[error("Latent dimension mismatch: expected 256, got {0}")]
    LatentDimMismatch(usize),
}

// ── Force-field parameters per atom ─────────────────────────────────────────

/// Per-atom Lennard-Jones + Coulomb parameters decoded from the GNN latent.
#[derive(Clone, Debug)]
pub struct AtomParams {
    pub epsilon: f32, // LJ well depth (kcal/mol)
    pub sigma:   f32, // LJ radius (Å)
    pub charge:  f32, // partial charge (e)
}

/// Decode the 256-dim GNN latent into per-atom force-field params.
/// Layout: latent[i*3 .. i*3+3] = (ε, σ, q) for atom i.
pub fn decode_latent(latent: ArrayView1<f32>, n_atoms: usize) -> Result<Vec<AtomParams>, EngineError> {
    if latent.len() < n_atoms * 3 {
        return Err(EngineError::LatentDimMismatch(latent.len()));
    }
    Ok((0..n_atoms)
        .map(|i| AtomParams {
            epsilon: latent[i * 3].abs()      + 0.01, // strictly positive
            sigma:   latent[i * 3 + 1].abs()  + 0.5,  // Å, strictly positive
            charge:  latent[i * 3 + 2],
        })
        .collect())
}

// ── Pairwise energy / force kernels ─────────────────────────────────────────

/// Scalar LJ + Coulomb for one atom pair.
/// Returns (E_pair, fx, fy, fz) where the force acts on atom i.
#[inline(always)]
pub fn pair_energy_scalar(
    dx: f32, dy: f32, dz: f32,
    eps_i: f32, sig_i: f32, q_i: f32,
    eps_j: f32, sig_j: f32, q_j: f32,
) -> (f32, f32, f32, f32) {
    let r2 = dx * dx + dy * dy + dz * dz;
    if r2 > LJ_CUTOFF_SQ || r2 < 1e-10 {
        return (0.0, 0.0, 0.0, 0.0);
    }
    let r     = r2.sqrt();
    let r_inv = 1.0 / r;

    // Lorentz-Berthelot combining rules
    let eps_ij = (eps_i * eps_j).sqrt();
    let sig_ij = 0.5 * (sig_i + sig_j);

    let s_r   = sig_ij * r_inv;
    let s_r6  = s_r.powi(6);
    let s_r12 = s_r6 * s_r6;

    let e_lj       = 4.0 * eps_ij * (s_r12 - s_r6);
    let de_lj_dr   = 4.0 * eps_ij * r_inv * (-12.0 * s_r12 + 6.0 * s_r6);
    let e_coul     = COULOMB_K * q_i * q_j * r_inv;
    let de_coul_dr = -e_coul * r_inv;

    let f_mag = -(de_lj_dr + de_coul_dr) * r_inv; // |F| / r

    (e_lj + e_coul, f_mag * dx, f_mag * dy, f_mag * dz)
}

/// AVX-512 vectorised pairwise energy over blocks of 16 atom pairs.
///
/// # Safety
/// Requires AVX-512F; caller verifies via `is_x86_feature_detected!("avx512f")`.
#[cfg(feature = "avx512")]
#[target_feature(enable = "avx512f")]
pub unsafe fn pair_energy_avx512(
    pos:      &Array2<f32>,
    params:   &[AtomParams],
    energies: &mut Array1<f32>,
    forces:   &mut Array2<f32>,
) {
    let n = pos.nrows();

    for i in 0..n {
        let xi    = pos[[i, 0]];
        let yi    = pos[[i, 1]];
        let zi    = pos[[i, 2]];
        let eps_i = params[i].epsilon;
        let sig_i = params[i].sigma;
        let q_i   = params[i].charge;

        let xi_v      = _mm512_set1_ps(xi);
        let yi_v      = _mm512_set1_ps(yi);
        let zi_v      = _mm512_set1_ps(zi);
        let eps_i_v   = _mm512_set1_ps(eps_i);
        let sig_i_v   = _mm512_set1_ps(sig_i);
        let q_i_v     = _mm512_set1_ps(q_i);
        let cutoff_v  = _mm512_set1_ps(LJ_CUTOFF_SQ);
        let four_v    = _mm512_set1_ps(4.0);
        let k_coul_v  = _mm512_set1_ps(COULOMB_K);
        let half_v    = _mm512_set1_ps(0.5);
        let six_v     = _mm512_set1_ps(6.0);
        let eps_floor = _mm512_set1_ps(1e-10_f32);

        let mut j = i + 1;

        // 16-wide SIMD kernel; i<j so each pair is visited exactly once
        while j + 16 <= n {
            let xj = _mm512_set_ps(
                pos[[j+15,0]], pos[[j+14,0]], pos[[j+13,0]], pos[[j+12,0]],
                pos[[j+11,0]], pos[[j+10,0]], pos[[j+9,0]],  pos[[j+8,0]],
                pos[[j+7,0]],  pos[[j+6,0]],  pos[[j+5,0]],  pos[[j+4,0]],
                pos[[j+3,0]],  pos[[j+2,0]],  pos[[j+1,0]],  pos[[j,0]],
            );
            let yj = _mm512_set_ps(
                pos[[j+15,1]], pos[[j+14,1]], pos[[j+13,1]], pos[[j+12,1]],
                pos[[j+11,1]], pos[[j+10,1]], pos[[j+9,1]],  pos[[j+8,1]],
                pos[[j+7,1]],  pos[[j+6,1]],  pos[[j+5,1]],  pos[[j+4,1]],
                pos[[j+3,1]],  pos[[j+2,1]],  pos[[j+1,1]],  pos[[j,1]],
            );
            let zj = _mm512_set_ps(
                pos[[j+15,2]], pos[[j+14,2]], pos[[j+13,2]], pos[[j+12,2]],
                pos[[j+11,2]], pos[[j+10,2]], pos[[j+9,2]],  pos[[j+8,2]],
                pos[[j+7,2]],  pos[[j+6,2]],  pos[[j+5,2]],  pos[[j+4,2]],
                pos[[j+3,2]],  pos[[j+2,2]],  pos[[j+1,2]],  pos[[j,2]],
            );
            let eps_j = _mm512_set_ps(
                params[j+15].epsilon, params[j+14].epsilon, params[j+13].epsilon, params[j+12].epsilon,
                params[j+11].epsilon, params[j+10].epsilon, params[j+9].epsilon,  params[j+8].epsilon,
                params[j+7].epsilon,  params[j+6].epsilon,  params[j+5].epsilon,  params[j+4].epsilon,
                params[j+3].epsilon,  params[j+2].epsilon,  params[j+1].epsilon,  params[j].epsilon,
            );
            let sig_j = _mm512_set_ps(
                params[j+15].sigma, params[j+14].sigma, params[j+13].sigma, params[j+12].sigma,
                params[j+11].sigma, params[j+10].sigma, params[j+9].sigma,  params[j+8].sigma,
                params[j+7].sigma,  params[j+6].sigma,  params[j+5].sigma,  params[j+4].sigma,
                params[j+3].sigma,  params[j+2].sigma,  params[j+1].sigma,  params[j].sigma,
            );
            let q_j = _mm512_set_ps(
                params[j+15].charge, params[j+14].charge, params[j+13].charge, params[j+12].charge,
                params[j+11].charge, params[j+10].charge, params[j+9].charge,  params[j+8].charge,
                params[j+7].charge,  params[j+6].charge,  params[j+5].charge,  params[j+4].charge,
                params[j+3].charge,  params[j+2].charge,  params[j+1].charge,  params[j].charge,
            );

            let dx = _mm512_sub_ps(xi_v, xj);
            let dy = _mm512_sub_ps(yi_v, yj);
            let dz = _mm512_sub_ps(zi_v, zj);

            let r2 = _mm512_fmadd_ps(dx, dx,
                         _mm512_fmadd_ps(dy, dy,
                             _mm512_mul_ps(dz, dz)));
            let active: __mmask16 =
                _mm512_cmp_ps_mask(r2, cutoff_v,  _CMP_LT_OS) &
                _mm512_cmp_ps_mask(r2, eps_floor, _CMP_GT_OS);

            let r     = _mm512_sqrt_ps(r2);
            let r_inv = _mm512_rcp14_ps(r);

            let eps_ij = _mm512_sqrt_ps(_mm512_mul_ps(eps_i_v, eps_j));
            let sig_ij = _mm512_mul_ps(half_v, _mm512_add_ps(sig_i_v, sig_j));

            let s_r   = _mm512_mul_ps(sig_ij, r_inv);
            let s_r2  = _mm512_mul_ps(s_r,  s_r);
            let s_r4  = _mm512_mul_ps(s_r2, s_r2);
            let s_r6  = _mm512_mul_ps(s_r4, s_r2);
            let s_r12 = _mm512_mul_ps(s_r6, s_r6);

            let e_lj = _mm512_mul_ps(
                four_v,
                _mm512_mul_ps(eps_ij, _mm512_sub_ps(s_r12, s_r6)),
            );
            let e_coul = _mm512_mul_ps(
                k_coul_v,
                _mm512_mul_ps(_mm512_mul_ps(q_i_v, q_j), r_inv),
            );
            let e_pair = _mm512_add_ps(e_lj, e_coul);

            let de_lj_dr = _mm512_mul_ps(
                _mm512_mul_ps(four_v, _mm512_mul_ps(eps_ij, r_inv)),
                _mm512_fmadd_ps(_mm512_set1_ps(-12.0), s_r12,
                                _mm512_mul_ps(six_v, s_r6)),
            );
            let de_coul_dr = _mm512_mul_ps(
                _mm512_set1_ps(-1.0),
                _mm512_mul_ps(e_coul, r_inv),
            );
            let f_mag = _mm512_mul_ps(
                _mm512_set1_ps(-1.0),
                _mm512_mul_ps(_mm512_add_ps(de_lj_dr, de_coul_dr), r_inv),
            );

            let fx = _mm512_mul_ps(f_mag, dx);
            let fy = _mm512_mul_ps(f_mag, dy);
            let fz = _mm512_mul_ps(f_mag, dz);

            // i<j — each pair counted exactly once, no factor of 1/2 needed
            let e_masked = _mm512_maskz_mov_ps(active, e_pair);
            energies[i] += _mm512_reduce_add_ps(e_masked);

            let fx_arr: [f32; 16] = std::mem::transmute(_mm512_maskz_mov_ps(active, fx));
            let fy_arr: [f32; 16] = std::mem::transmute(_mm512_maskz_mov_ps(active, fy));
            let fz_arr: [f32; 16] = std::mem::transmute(_mm512_maskz_mov_ps(active, fz));
            for k in 0..16 {
                forces[[j + k, 0]] -= fx_arr[k];
                forces[[j + k, 1]] -= fy_arr[k];
                forces[[j + k, 2]] -= fz_arr[k];
            }
            forces[[i, 0]] += fx_arr.iter().sum::<f32>();
            forces[[i, 1]] += fy_arr.iter().sum::<f32>();
            forces[[i, 2]] += fz_arr.iter().sum::<f32>();

            j += 16;
        }

        // Scalar tail for remaining j atoms
        while j < n {
            let dx = xi - pos[[j, 0]];
            let dy = yi - pos[[j, 1]];
            let dz = zi - pos[[j, 2]];
            let (e, fx, fy, fz) = pair_energy_scalar(
                dx, dy, dz,
                eps_i, sig_i, q_i,
                params[j].epsilon, params[j].sigma, params[j].charge,
            );
            energies[i]    += e;
            forces[[i, 0]] += fx;
            forces[[i, 1]] += fy;
            forces[[i, 2]] += fz;
            forces[[j, 0]] -= fx;
            forces[[j, 1]] -= fy;
            forces[[j, 2]] -= fz;
            j += 1;
        }
    }
}

// ── Velocity-Verlet integrator ────────────────────────────────────────────────

pub struct MDState {
    pub positions:  Array2<f32>, // [N, 3]  Å
    pub velocities: Array2<f32>, // [N, 3]  Å/ps
    pub forces:     Array2<f32>, // [N, 3]  kcal/(mol·Å)
    pub masses:     Array1<f32>, // [N]     amu
    pub params:     Vec<AtomParams>,
    pub energies:   Array1<f32>, // [N]     kcal/mol (per-atom contribution)
    pub dt:         f32,         // ps
    pub step_count: usize,
}

impl MDState {
    pub fn new(
        positions: Array2<f32>,
        masses:    Array1<f32>,
        params:    Vec<AtomParams>,
        dt:        f32,
    ) -> Self {
        let n = positions.nrows();
        Self {
            positions,
            velocities: Array2::zeros((n, 3)),
            forces:     Array2::zeros((n, 3)),
            masses,
            params,
            energies:   Array1::zeros(n),
            dt,
            step_count: 0,
        }
    }

    /// Recompute forces and per-atom energy contributions from current positions.
    pub fn compute_forces(&mut self) {
        self.forces.fill(0.0);
        self.energies.fill(0.0);

        #[cfg(feature = "avx512")]
        {
            if is_x86_feature_detected!("avx512f") {
                unsafe {
                    pair_energy_avx512(
                        &self.positions,
                        &self.params,
                        &mut self.energies,
                        &mut self.forces,
                    );
                }
                return;
            }
        }

        // Scalar fallback — i<j loop, each pair visited exactly once
        let n = self.positions.nrows();
        for i in 0..n {
            for j in (i + 1)..n {
                let dx = self.positions[[i, 0]] - self.positions[[j, 0]];
                let dy = self.positions[[i, 1]] - self.positions[[j, 1]];
                let dz = self.positions[[i, 2]] - self.positions[[j, 2]];
                let (e, fx, fy, fz) = pair_energy_scalar(
                    dx, dy, dz,
                    self.params[i].epsilon, self.params[i].sigma, self.params[i].charge,
                    self.params[j].epsilon, self.params[j].sigma, self.params[j].charge,
                );
                self.energies[i]    += e;
                self.forces[[i, 0]] += fx;
                self.forces[[i, 1]] += fy;
                self.forces[[i, 2]] += fz;
                self.forces[[j, 0]] -= fx;
                self.forces[[j, 1]] -= fy;
                self.forces[[j, 2]] -= fz;
            }
        }
    }

    /// One velocity-Verlet step.
    pub fn verlet_step(&mut self) {
        let n   = self.positions.nrows();
        let dt  = self.dt;
        let dt2 = 0.5 * dt;

        // Half-kick velocities, then drift positions
        for i in 0..n {
            let inv_m = 1.0 / self.masses[i];
            for k in 0..3 {
                self.velocities[[i, k]] += dt2 * self.forces[[i, k]] * inv_m;
                self.positions[[i, k]]  += dt  * self.velocities[[i, k]];
            }
        }

        self.compute_forces();

        // Second half-kick
        for i in 0..n {
            let inv_m = 1.0 / self.masses[i];
            for k in 0..3 {
                self.velocities[[i, k]] += dt2 * self.forces[[i, k]] * inv_m;
            }
        }
        self.step_count += 1;
    }

    /// Run `n` Verlet steps — the single blocking call exposed to Python.
    pub fn run(&mut self, n: usize) {
        self.compute_forces();
        for _ in 0..n {
            self.verlet_step();
        }
    }

    /// Total potential energy in kcal/mol.
    pub fn total_energy(&self) -> f32 {
        self.energies.sum()
    }
}

// ── Gradient: dE/d_latent (VJP for backprop) ─────────────────────────────────

/// Forward-difference VJP: grad[k] = grad_output * (E(latent + eps*e_k) - E(latent)) / eps.
/// Evaluates only potential energy (no MD steps), so masses are not used here.
pub fn energy_vjp(
    positions:   &Array2<f32>,
    latent:      &Array1<f32>,
    n_atoms:     usize,
    grad_output: f32,
) -> Array1<f32> {
    let eps = 1e-4_f32;
    let mut grad = Array1::zeros(latent.len());

    let e_base = {
        let params = decode_latent(latent.view(), n_atoms).unwrap();
        let mut s  = MDState::new(positions.clone(), Array1::ones(n_atoms), params, 0.001);
        s.compute_forces();
        s.total_energy()
    };

    for k in 0..latent.len() {
        let mut lat_p = latent.clone();
        lat_p[k] += eps;
        let e_p = {
            let params = decode_latent(lat_p.view(), n_atoms).unwrap();
            let mut s  = MDState::new(positions.clone(), Array1::ones(n_atoms), params, 0.001);
            s.compute_forces();
            s.total_energy()
        };
        grad[k] = grad_output * (e_p - e_base) / eps;
    }
    grad
}

// ── PyO3 binding ─────────────────────────────────────────────────────────────

/// Python-facing wrapper around MDState.
/// Non-Send via PhantomData to prevent the GIL from releasing Rust state
/// while a PyTorch backward pass still holds a reference to this engine.
#[pyclass]
pub struct Engine {
    state:     MDState,
    _lifetime: PhantomData<*const ()>,
}

#[pymethods]
impl Engine {
    /// Construct from numpy arrays.
    ///
    /// Args:
    ///   positions: np.ndarray[float32, (N, 3)]
    ///   masses:    np.ndarray[float32, (N,)]
    ///   latent:    np.ndarray[float32, (256,)] — zero-copy view of GNN output
    ///   dt:        timestep in ps (default 0.001)
    #[new]
    #[pyo3(signature = (positions, masses, latent, dt=0.001))]
    fn new(
        _py:       Python<'_>,
        positions: numpy::PyReadonlyArray2<f32>,
        masses:    numpy::PyReadonlyArray1<f32>,
        latent:    numpy::PyReadonlyArray1<f32>,
        dt:        f32,
    ) -> PyResult<Self> {
        let pos     = positions.as_array().to_owned();
        let mas     = masses.as_array().to_owned();
        let lat     = latent.as_array();
        let n_atoms = pos.nrows();

        let params = decode_latent(lat, n_atoms)
            .map_err(|e| PyValueError::new_err(e.to_string()))?;

        Ok(Self {
            state:     MDState::new(pos, mas, params, dt),
            _lifetime: PhantomData,
        })
    }

    /// Run `n` MD steps in Rust (GIL released). Returns total potential energy (kcal/mol).
    fn step(&mut self, py: Python<'_>, n: usize) -> PyResult<f32> {
        py.allow_threads(|| self.state.run(n));
        Ok(self.state.total_energy())
    }

    fn positions<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, numpy::PyArray2<f32>>> {
        Ok(numpy::PyArray2::from_array_bound(py, &self.state.positions))
    }

    fn forces<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, numpy::PyArray2<f32>>> {
        Ok(numpy::PyArray2::from_array_bound(py, &self.state.forces))
    }

    /// Compute dE/d_latent for the backward pass (GIL released).
    /// Gradient is evaluated at the post-MD geometry stored in self.state.positions.
    fn energy_grad_latent<'py>(
        &self,
        py:          Python<'py>,
        latent:      numpy::PyReadonlyArray1<f32>,
        grad_output: f32,
    ) -> PyResult<Bound<'py, numpy::PyArray1<f32>>> {
        let n_atoms = self.state.positions.nrows();
        let lat     = latent.as_array().to_owned();
        let grad    = py.allow_threads(|| {
            energy_vjp(&self.state.positions, &lat, n_atoms, grad_output)
        });
        Ok(numpy::PyArray1::from_array_bound(py, &grad))
    }

    fn total_energy(&self) -> f32 {
        self.state.total_energy()
    }

    fn step_count(&self) -> usize {
        self.state.step_count
    }
}

// ── Module registration ───────────────────────────────────────────────────────

#[pymodule]
fn md_engine(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Engine>()?;
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
    Ok(())
}
